# Deployment do MongoDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0.5
        ports: 
          - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: mongouser
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: mongopwd
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
  type: ClusterIP


# Deployment do rotten-potatoes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rp-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      projectName: rp-web
    
  template:
    metadata:
      labels:
        app: rp
        projectName: rp-web
    spec:
      containers:
        - name: rp-pod
          image: brunosilvagarciadocker/rotten-potatoes:v1.0.3
          ports:
            - containerPort: 5000
          env:
           - name: MONGODB_HOST
             value: mongodb
           - name: MONGODB_PORT
             value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: service-rp
spec:
  selector:
    projectName: rp-web
  ports:
  - protocol: TCP
    port: 5000
    nodePort: 30050
  type: LoadBalancer
